user_collection = "users"
games_collection = "games"

username = "username"
password = "password"
friends = "friends"
api_key = "api"
games_list_key = "games"

game_id = "gameID"
players_key = "users"
player_trade = "trades"
privacy = "privacy"
starting_money = "startMoney"
balance = "balance"
start_time = "startTime"
end_time = "endTime"